# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0011_auto_20170906_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_created', models.DateTimeField(verbose_name='Created date')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('main_image', models.ImageField(upload_to='issue', verbose_name='Main image')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
            },
        ),
        migrations.CreateModel(
            name='IssueCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.PositiveSmallIntegerField(choices=[(1, 'Item'), (2, 'Image')], default=1, verbose_name='Content type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='issue', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Issue cell',
                'verbose_name_plural': 'Issue cells',
            },
        ),
        migrations.CreateModel(
            name='IssueRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('display_type', models.PositiveSmallIntegerField(choices=[(1, 'Split'), (2, 'Join')], default=2, verbose_name='Display type')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raws', to='featured.Issue', verbose_name='Issue')),
            ],
            options={
                'verbose_name': 'Issue Raw',
                'verbose_name_plural': 'Issue Raws',
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='issuecell',
            name='issue_raw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='featured.IssueRaw', verbose_name='Issue raw'),
        ),
        migrations.AddField(
            model_name='issuecell',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Item', verbose_name='Item'),
        ),
    ]
