# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueraw',
            name='cell_counts',
            field=models.PositiveIntegerField(choices=[(1, 'One slot'), (2, 'Two slots'), (3, 'Three slots'), (4, 'Four slots'), (5, 'Big and small'), (6, 'Small and big')], default=1, verbose_name='Cells counts'),
        ),
        migrations.AddField(
            model_name='issueraw',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extralarge', 'Extralarge')], default='small', max_length=10, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='when_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='issueraw',
            name='display_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Separated'), (1, 'Join')], default=1, verbose_name='Display type'),
        ),
    ]
