# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('main_image', models.ImageField(upload_to='brands', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Брэнд',
                'verbose_name_plural': 'Брэнды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
                ('main_image', models.ImageField(upload_to='categories', verbose_name='Изображение')),
                ('type', models.IntegerField(choices=[(1, 'Катеогрия'), (2, 'Подарок')], verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='items', verbose_name='Изображение')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('link', models.URLField(verbose_name='Ссылка на внешний рессурс')),
                ('description', models.TextField(verbose_name='Описание')),
                ('site_name', models.CharField(blank=True, help_text='из поля "Ссылка" имя сайта береться автоматически, не стоит заполнять это поля если имя сайта вас устраивает', max_length=30, null=True, verbose_name='Название сайта')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogue.Brand', verbose_name='Производитель')),
                ('categories', models.ManyToManyField(related_name='items', to='catalogue.Category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
