# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Ссылка на товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='when_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Когда создан'),
            preserve_default=False,
        ),
    ]
