# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 12:14
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('catalogue', '0002_auto_20170810_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
