# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20170810_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-when_created',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='item',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Есть в наличии'),
        ),
    ]
