# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20170812_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='catalogue.Item', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='like_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='catalogue.LikeList', verbose_name='Список понравившегось'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likelist',
            name='when_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
