# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20170812_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='item',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like_list',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='LikeList',
        ),
    ]
