# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20170815_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='related_items',
            field=models.ManyToManyField(blank=True, null=True, related_name='_item_related_items_+', to='catalogue.Item'),
        ),
    ]
