# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_item_related_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='related_items',
        ),
    ]
