# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_remove_item_related_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.PositiveSmallIntegerField(default=0, help_text='Determines order of the products. A product with a higher value will appear before one with a lower ranking.', verbose_name='Ranking')),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_recommendations', to='catalogue.Item', verbose_name='Primary product')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Item', verbose_name='Рекомендуемые продукты')),
            ],
            options={
                'verbose_name': 'Product related',
                'verbose_name_plural': 'Product related',
                'ordering': ['primary', '-ranking'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='related_items',
            field=models.ManyToManyField(blank=True, through='catalogue.RelatedItems', to='catalogue.Item'),
        ),
        migrations.AlterUniqueTogether(
            name='relateditems',
            unique_together=set([('primary', 'recommendation')]),
        ),
    ]
