# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20170816_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='main_image',
            field=models.ImageField(upload_to='brands', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='main_image',
            field=models.ImageField(upload_to='categories', verbose_name='Main image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.IntegerField(choices=[(1, 'Category'), (2, 'Gift')], verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='item',
            name='additional_likes',
            field=models.IntegerField(default=0, verbose_name='Additional likes'),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogue.Brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(related_name='items', to='catalogue.Category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Enable'),
        ),
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.URLField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=models.ImageField(upload_to='items', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='site_name',
            field=models.CharField(blank=True, help_text='from field "Slug" site name set auto, don\'t fill this field if site name is good for you', max_length=30, null=True, verbose_name='Site name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='item',
            name='when_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='When created'),
        ),
    ]
