# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 12:59
from __future__ import unicode_literals

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20170907_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='background_image',
            field=models.ImageField(default='', upload_to=catalogue.models.Brand.get_upload_path, verbose_name='Background image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_image',
            field=models.ImageField(default='', upload_to=catalogue.models.Brand.get_upload_path, verbose_name='Logo image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='background_image',
            field=models.ImageField(default='', upload_to=catalogue.models.Category.get_upload_path, verbose_name='Background image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='logo_image',
            field=models.ImageField(default='', upload_to=catalogue.models.Category.get_upload_path, verbose_name='Logo image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='main_image',
            field=models.ImageField(upload_to=catalogue.models.Brand.get_upload_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='main_image',
            field=models.ImageField(upload_to=catalogue.models.Category.get_upload_path, verbose_name='Main image'),
        ),
    ]
