# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 13:01
from __future__ import unicode_literals

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20170911_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=catalogue.models.Brand.get_upload_path, verbose_name='Background image'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=catalogue.models.Brand.get_upload_path, verbose_name='Logo image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=catalogue.models.Category.get_upload_path, verbose_name='Background image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=catalogue.models.Category.get_upload_path, verbose_name='Logo image'),
        ),
    ]
