# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20170911_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_prime',
            field=models.BooleanField(default=False, verbose_name='Prime'),
        ),
    ]
