# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0007_auto_20170815_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='catalogue.Item', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='LikeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='like_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='likelist.LikeList', verbose_name='Список понравившегось'),
        ),
    ]
