# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20170815_1324'),
        ('likelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likelist',
            options={'verbose_name': 'Список понравившегось', 'verbose_name_plural': 'Списки понравившегось'},
        ),
        migrations.AddField(
            model_name='like',
            name='when_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('like_list', 'item')]),
        ),
    ]
