# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likelist', '0002_auto_20170815_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likelist',
            options={'verbose_name': 'Like lists', 'verbose_name_plural': 'Like list'},
        ),
        migrations.AlterField(
            model_name='like',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='catalogue.Item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='likelist.LikeList', verbose_name='Like list'),
        ),
        migrations.AlterField(
            model_name='likelist',
            name='when_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create date'),
        ),
    ]
